- name: Create Inception project directory
  file:
    path: "{{ ansible_env.HOME }}/inception"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'

- name: copy Inception configuration files to VM
  copy:
    src: ./inception/
    dest: "{{ ansible_env.HOME }}/inception/"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'
    directory_mode: '0755'
  become: true

- name: Create persistent data directories
  file:
    path: "/home/data/{{ item }}"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0775'
    recurse: yes
  become: true
  loop:
    - wordpress
    - mariadb

- name: start Inception project
  shell:
    cmd: docker compose --env-file ./secrets/.env up -d --build
    chdir: "{{ ansible_env.HOME }}/inception/srcs"
  become: true