services:
    
    nginx:
      image: nginx:stable-alpine
      container_name: nginx
      restart: always
      ports:
        - "443:443"
        - "80:80"
      volumes:
        - ./requeriments/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./requeriments/nginx/certs/ssl-cert.key:/etc/nginx/certs/ssl-cert.key:ro
        - ./requeriments/nginx/certs/ssl-cert.pem:/etc/nginx/certs/ssl-cert.pem:ro
      depends_on:
        wordpress:
          condition: service_started
      networks:
        - inception-net
    
    wordpress:
      image: wordpress:fpm
      volumes:
        - wp_data:/var/www/html
      restart: always
      environment:
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        WORDPRESS_DB_USER: ${MYSQL_USER}
        WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      env_file: 
        - ./secrets/.env
      depends_on:
        mariadb:
          condition: service_healthy
      networks:
        - inception-net

    wp-auto-config:
      image: wordpress:cli
      volumes:
        - wp_data:/var/www/html
        - ./wp-init.sh:/usr/local/bin/wp-init.sh
      user: "33:33"
      entrypoint: ["/bin/sh", "/usr/local/bin/wp-init.sh"]
      depends_on:
        - mariadb
        - wordpress
      environment:
        WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
        WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        WORDPRESS_DB_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
      env_file: 
        - ./secrets/.env
      networks:
        - inception-net

    mariadb:
      image: mariadb:10.11
      container_name: mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      env_file: 
        - ./secrets/.env
      volumes:
        - db_data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 5
      networks:
        - inception-net

networks:
  inception-net:

volumes:
    wp_data:    
    db_data:
